### ISSUE TITLE
Merge translateX and translateY

### ISSUE THREAD

**Issue by bfred-it** [ben-eb/postcss-reduce-transforms#11]
# Input

```css
a{
  transform: translateX(20px) translateY(10px);
}
```
# Desired output

```css
a{
  transform: translate3d(20px, 10px, 0);
}
```
