### ISSUE TITLE
Merge transforms into single matrix when possible

### ISSUE THREAD

**Issue by bfred-it** [ben-eb/postcss-reduce-transforms#12]
All transform-functions can be condensed into `matrix()` or `matrix3d()` but:

- only `deg`, `px` and unitless values are supported by matrix afaik
- `rotate*` and `skew*` are often not effective since they result into values like 0.201201201
- 3d functions are often not effective since matrix3d starts at 41 characters

# Input

```css
a {
  transform: scale(2) translate(20px);

  transform: scale(2) translate(20px) rotate(45deg);

  transform: translateZ(100px) perspective(100px);

  transform: translateZ(100px) translateX(100px) perspective(100px);
}
```

# Desired output

```css
a {
  transform: matrix(2,0,0,2,40,0);

  transform: matrix(1.41421,1.41421,-1.41421,1.41421,40,0); /* nope */
  transform: matrix(2,0,0,2,40,0) rotate(45deg); /* yep */

  transform: matrix3d(1,0,0,0,0,1,0,0,0,0,0,0,0,0,1,1); /* nope */

  transform: matrix3d(1,0,0,0,0,1,0,0,-1,0,0,-0.01,100,0,100,1); /* yep */
}
```
