### ISSUE TITLE
transform:scale(1,1)

### ISSUE THREAD

**Issue by lomocc** [ben-eb/postcss-reduce-transforms#2]
I have a style looks like:

```
@keyframes centreShrinkY-animation {
  0% {  
  transform:scale(1, 1);
  }
  100%{
  transform:scale(1, 0);
  }
}
```

or

```
@keyframes centreShrinkY-animation {
  0% {
  transform:scale3d(1, 1, 1);
  }
  100%{
  transform:scale3d(1, 0, 1);
  }
}
```

It doesn`t work on chrome50 when I use webpack -p.
because it is going to be

```
@keyframes centreShrinkY-animation {
  0% {
  transform:scale(1);
  }
  100%{
  transform:scaleY(0);
  }
}
```

May I?

**Comment by ben-eb** [comment]
Can you provide more information? It works for me on Chrome 49 & Firefox 44 (both animations are identical), using this CSS;

```css
div {
  height: 100px;
  width: 100px;
  background: blue;
  animation: b .5s infinite alternate linear;
}

@keyframes a {
  0% {  
    transform: scale(1, 1);
  }
  100% {
    transform: scale(1, 0);
  }
}

@keyframes b {
  0% {  
    transform: scale(1);
  }
  100% {
    transform: scaleY(0);
  }
}
```
